remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Mohammed Fayed Blog]
description: [A playground for my experiments]

show_downloads: false  # indicate whether to provide a download URL
# google_analytics: [Your Google Analytics tracking ID]
